// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package links

import (
	"database/sql"
	"time"
)

type Link struct {
	Source      string
	Destination string
	Description sql.NullString
	Created     time.Time
}

type View struct {
	ID      int64
	Path    string
	Ip      string
	Created time.Time
}
